site_name: TF2 HUD Editor
site_author: criticalflaw
theme:
    language: en
    name: material
    logo: resources/logo.png
    favicon: resources/logo.png
    palette:
        scheme: slate
        primary: amber
        accent: orange
repo_name: GitHub
site_url: https://www.editor.criticalflaw.ca/
repo_url: https://github.com/CriticalFlaw/TF2HUD.Editor/
nav:
    - Home: 'index.md'
    - Installation: 'install.md'
    - Troubleshooting: 'troubleshoot.md'
    - How to Contribute: 'contribute.md'
    - Adding your HUD:
        - 1. Base Settings: 'json/base.md'
        - 2. Controls: 'json/controls.md'
        - 3. Menu Option: 'json/options.md'
markdown_extensions:
    - admonition
    - pymdownx.superfences
plugins:
    - search
    - git-revision-date-localized:
        type: date
extra_css:
    - resources/teamfortress.css
extra:
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/CriticalFlaw/TF2HUD.Editor
        - icon: fontawesome/brands/twitter
          link: https://twitter.com/CriticalFlaw_
        - icon: fontawesome/brands/discord
          link: https://discord.gg/hTdtK9vBhE