site_name: TF2 HUD Editor
site_author: criticalflaw
theme:
    language: en
    name: material
    logo: resources/logo.png
    favicon: resources/logo.png
    features:
        - navigation.expand
    palette:
        - scheme: default
		  primary: indigo
		  accent: orange
		  toggle:
			icon: material/toggle-switch-off-outline
			name: Switch to dark mode
        - scheme: slate
		  primary: indigo
		  accent: orange
		  toggle:
			icon: material/toggle-switch
			name: Switch to light mode
repo_name: GitHub
site_url: https://www.editor.criticalflaw.ca/
repo_url: https://github.com/CriticalFlaw/TF2HUD.Editor/
nav:
    - Home: 'index.md'
    - Installation: 'install.md'
    - Troubleshooting: 'troubleshoot.md'
    - How to Contribute: 'contribute.md'
    - Adding your HUD: 
        - 0. Introduction: 'json/intro.md'
        - 1. Main Settings: 'json/base.md'
        - 2. User Controls: 'json/controls.md'
        - 3. List Options: 'json/options.md'
hide:
  - toc
google_analytics:
  - G-Q532RTS1WC
  - auto
markdown_extensions:
    - admonition
    - pymdownx.superfences
plugins:
    - search
    - git-revision-date-localized:
        type: date
extra_css:
    - resources/teamfortress.css
extra:
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/CriticalFlaw/TF2HUD.Editor
        - icon: fontawesome/brands/twitter
          link: https://twitter.com/CriticalFlaw_
        - icon: fontawesome/brands/discord
          link: https://discord.gg/hTdtK9vBhE