site_name: TF2 HUD Editor
site_author: criticalflaw
theme:
    language: en
    name: material
    logo: resources/logo.png
    favicon: resources/logo.png
    palette:
        scheme: slate
        primary: amber
        accent: orange
repo_name: GitHub
site_url: https://www.criticalflaw.ca/hud-editor/
repo_url: https://github.com/CriticalFlaw/TF2HUD.Editor/
nav:
    - Home: 'index.md'
    - Installation: 'install.md'
    - Troubleshooting: 'troubleshoot.md'
    - How to Contribute: 'contribute.md'
    - JSON Customizations: 'json.md'
markdown_extensions:
    - admonition
    - pymdownx.superfences
plugins:
    - search
    - git-revision-date-localized:
        type: date
extra_css:
    - resources/teamfortress.css
extra:
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/CriticalFlaw/TF2HUD.Editor
        - icon: fontawesome/brands/twitter
          link: https://twitter.com/CriticalFlaw_