name: "CodeQL"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '20 7 * * 3'

jobs:
  analyze:
    name: Analyze
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        language: [ 'csharp' ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # Initializes the CodeQL tools for scanning.
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: ${{ matrix.language }}

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.0
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    - name: Restore NuGet Packages
      run: nuget restore src/TF2HUD.Editor.sln

    - name: Build App
      run: msbuild src/TF2HUD.Editor.sln /p:Configuration=Debug /p:Platform=x64 /p:UseSharedCompilation=false

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
